name: Deploy Backend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean backend folder on EC2 (except .env)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/backend
            # Borrar todo excepto el archivo .env
            sudo find . -mindepth 1 ! -name '.env' -exec rm -rf {} +
            sudo chown -R ubuntu:www-data /var/www/html/backend

      - name: Upload Backend to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/var/www/html/backend"
          rm: false

      - name: Setup Backend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/backend
            composer install --no-dev

            # Crear directorio writable/cache con permisos adecuados
            sudo mkdir -p writable/cache
            sudo chown -R www-data:ubuntu writable
            sudo chmod -R 775 writable

            # Asegurar permisos correctos
            sudo chown -R www-data:www-data /var/www/html/backend
